### PR TITLE
Remove compiler lock + GCC update

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@jan-janssen Let's wait for the bot to issue a PR here. That way it will be able to track is own internal state in the normal way.

**Comment by jan-janssen** [comment]
@beckermr That is fine for me, I ultimately try to get https://github.com/conda-forge/damask-feedstock updated to gcc 9.3.0 as the current version requires gcc 8.X and I had to patch it and remove some modern modules to get it working with gcc 7.5 . Damask depends on petsc and petsc depends on superlu_dist that is why I was pushing for migrating superlu_dist.

**Comment by beckermr** [comment]
Sounds great! Thank you for the help and for looking in on things!

**Pull request closed without merging**
